# Generated by Django 5.2.14 on 2026-05-07 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.TextField()),
                ('duration', models.CharField(max_length=100)),
                ('age_range', models.CharField(max_length=50)),
                ('conditions', models.TextField(blank=True, null=True)),
                ('urgency', models.CharField(default='low', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultations.lead')),
            ],
        ),
    ]
