# Generated by Django 5.2.14 on 2026-05-08 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_consultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('screening_form_sent', 'Screening Form Sent'), ('screening_completed', 'Screening Completed'), ('doctor_chat_scheduled', 'Doctor Chat Scheduled'), ('consultation_done', 'Consultation Done'), ('cancelled', 'Cancelled')], default='screening_form_sent', max_length=25),
        ),
        migrations.AddField(
            model_name='consultation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='age_range',
            field=models.CharField(choices=[('0-12', 'Child (0-12 years)'), ('13-19', 'Teen (13-19 years)'), ('20-35', 'Young Adult (20-35 years)'), ('36-50', 'Adult (36-50 years)'), ('51+', 'Senior (51+ years)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='consultations.lead'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='urgency',
            field=models.CharField(choices=[('low', 'Low - General inquiry'), ('medium', 'Medium - Needs attention within 48 hours'), ('high', 'High - Needs attention within 24 hours')], default='low', max_length=10),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
