# Generated by Django 5.2.14 on 2026-05-08 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0004_lead_consent_lead_county_lead_gender_lead_referral_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='doctor_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='responded_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='response_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultation',
            name='response_whatsapp_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending - Awaiting doctor review'), ('screening_form_sent', 'Screening Form Sent'), ('screening_completed', 'Screening Completed'), ('doctor_chat_scheduled', 'Doctor Chat Scheduled'), ('consultation_done', 'Consultation Done'), ('cancelled', 'Cancelled')], default='pending', max_length=25),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='urgency',
            field=models.CharField(blank=True, choices=[('low', 'Low - General inquiry'), ('medium', 'Medium - Needs attention within 48 hours'), ('high', 'High - Needs attention within 24 hours')], default='low', max_length=10, null=True),
        ),
    ]
